name: Run Cypress Tests

# როდის უნდა გაშვებულიყო workflow
on:
  push:
    branches:
      - main # როდესაც main ბრანჩზე ხდება push
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # კოდის ჩასაწერად
      - name: Checkout repository
        uses: actions/checkout@v3

      # Node.js-ის ინსტალაცია
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Dependency-ების ინსტალაცია
      - name: Install dependencies
        run: npm ci

      # Cypress ტესტების გაშვება
      - name: Run Cypress tests
        run: npx cypress run
